[package]
name = "odilia-input"
version = "0.0.1"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>"]
description = "Input subsystem for the Odilia screen reader."
license = "gpl-3" # Not gpl-3-or-later
readme = "README.md"
repository = "https://github.com/odilia-app/odilia"
homepage = "https://odilia.app"
keywords = ["accessibility", "a11y", "input", "evdev", "linux"]
categories = ["accessibility"]
edition = "2021"
publish = false

[dependencies]
tokio = { version = "^1.19.0", features = ["full"] }
eyre = "^0.6.8"
rdev = { version = "0.5.1", features = ["unstable_grab"] }
lazy_static = "1.4.0"
tracing = "0.1.32"
nix = "0.23.1"
sysinfo = "0.23.5"
odilia-common = { path = "../common" }
once_cell = "1.13.0"
serde_json = "1.0.0"
