[workspace]
members = [
  "atspi",
  "common",
  "input",
  "odilia",
]

[profile.release]
lto = "thin"

[workspace.metadata.release]
allow-branch = ["main"]
# By default, crates will not be released or published
# These are overridden on a crate-by-crate basis
release = false
publish = false
shared-version = true
consolidate-commits = true
consolidate-pushes = true
pre-release-commit-message = "Release Odilia version {{version}}"
post-release-commit-message = "Post release version bump: version {{next_version}}"
tag-message = "{{crate_name}} version {{version}}"
dev-version-ext = "dev"
dev-version = true
pre-release-hook = ["cargo", "fmt"]
dependent-version = "upgrade"
