[workspace]
resolver = "2"
members = [
  "atspi",
	"atspi-proxies",
	"atspi-common",
  "atspi-connection",
]

[workspace.dependencies]
zbus = { version = "3.12.0", default-features = false }
tracing = "0.1.37"
enumflags2 = "0.7.7"
