[package]
name = "atspi-macros"
version = "0.2.0"
edition = "2021"
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>", "Tait Hoyem <tait@tait.tech>"]
description = "Macros to assist in various impl blocks for the `atspi` crate."
license = "MIT"
readme = "README.md"
repository = "https://github.com/odilia-app/atspi"
keywords = ["macros", "helper"]

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
