[package]
name = "atspi-connection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tokio = []
async-std = []

[dependencies]
enumflags2 = "^0.7.5"
atspi-proxies = { path = "../atspi-proxies/" }
atspi-common = { path = "../atspi-common/" }
futures-lite = "1.13.0"
zbus.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio-test = "0.4.2"
