[package]
name = "atspi-connection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
tracing = ["dep:tracing"]
async-std = ["zbus/async-io", "atspi-proxies/async-std", "atspi-common/async-std"]
tokio = ["zbus/tokio", "atspi-proxies/tokio", "atspi-common/tokio"]

[dependencies]
atspi-proxies = { path = "../atspi-proxies/" }
atspi-common = { path = "../atspi-common/" }
futures-lite = "1.13.0"
zbus.workspace = true
tracing = { optional = true, workspace = true }

[dev-dependencies]
tokio-test = "0.4.2"
