[package]
name = "atspi-common"
version = "0.1.0"
edition = "2021"
readme = "README.md"
categories = ["macros", "accessibility"]
keywords = ["Macros", "Accessibility"]
repository = "https://github.com/odilia-app/atspi"
description = "Primitive types used for sending and recieving Linux accessibility events."
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["async-std"]
async-std = ["zbus/async-io"]
tokio = ["zbus/tokio"]

[dependencies]
enumflags2 = "0.7.7"
serde = "1.0.162"
static_assertions = "1.1.0"
zbus_names = "2.5.0"
zvariant = "3.12.0"
zbus = { version = "3.12.0", optional = true, default-features = false }

[dev-dependencies]
byteorder = "1.4.3"
rename-item = "0.1.0"
