[package]
name = "atspi-common"
version = "0.1.0"
edition = "2021"
readme = "README.md"
categories = ["macros", "accessibility"]
keywords = ["Macros", "Accessibility"]
repository = "https://github.com/odilia-app/atspi"
description = "Primitive types used for sending and recieving Linux accessibility events."
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["async-std"]
async-std = ["zbus/async-io", "atspi-connection/async-std"]
tokio = ["zbus/tokio", "atspi-connection/tokio"]

[dependencies]
enumflags2 = "0.7.7"
serde = "1.0.162"
static_assertions = "1.1.0"
zbus_names = "2.5.0"
zvariant = "3.12.0"
zbus = { version = "3.12.0", optional = true }

[dev-dependencies]
atspi-proxies = { path = "../atspi-proxies/", default-features = false }
atspi-connection = { path = "../atspi-connection", default-features = false }
async-std = { version = "1.12.0", features = ["attributes"] }
futures-lite = "1.13.0"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
byteorder = "1.4.3"
rename-item = "0.1.0"
