[package]
name = "atspi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["proxies-async-std", "connection-async-std"]
proxies-async-std = ["atspi-proxies/async-std"]
proxies-tokio = ["atspi-proxies/tokio"]
connection-async-std = ["atspi-connection/async-std"]
connection-tokio = ["atspi-connection/tokio"]
unstable-proxy-traits = ["atspi-proxies/unstable-traits"]

[dependencies]
atspi-common = { path = "../atspi-common" }
atspi-proxies = { path = "../atspi-proxies", optional = true }
atspi-connection = { path = "../atspi-connection", optional = true }
